
name: Build Docker ali Image and Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          docker buildx build --platform linux/amd64 -t ali --load .
      - name: Save Docker image as tar
        run: |
          docker save ali -o ali.tar
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ali_amd
          path: ali.tar
